print("Olá, Usuario !")
nome=input("Como se chama? ")
print("Seja Bem-vindo(a)", nome)
dia=input("Em que dia você nasceu? ")
mes=input("Em que mês? ")
ano=input("Em que ano? ")
print(nome, "nasceu no dia", dia ,"de", mes , "de", ano,".")
print("agora, vamos fazer uma soma simples,", nome)
n1=input("Digite um numero. ")
n2=input("Agora, Digite outro numero. ")
print(n1 ,"+", n2 , "é igual a", int(n1)+int(n2))